s3:
  bucket: ${BUCKET_NAME_SPRING_SALE_TEST:empty}
  region: ${BUCKET_REGION_SPRING_SALE_TEST:empty}
server:
  port: 8002
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_spring_sale?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: postgres
    password: postgres
  mail:
    host: ${EMAIL_HOST_SPRING_SALE:smtp.gmail.com}
    port: ${EMAIL_PORT_SPRING_SALE:587}
    username: ${ACCOUNT_USERNAME_SPRING_SALE_TEST}
    password: ${ACCOUNT_PASSWORD_SPRING_SALE_TEST}
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true