server:
  port: 8002
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_spring_sale?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
